import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Header from "../components/header/header";
import SectionAbout from "../components/section-about/section-about";
import HeadingSecondary from "../components/heading-secondary/heading-secondary";
import Row from "../components/layout/row";
import Col1of2 from "../components/layout/col-1-of-2";

import HeadingTertiary from "../components/heading-tertiary/heading-tertiary";
import Paragraph from "../components/paragraph/paragraph";
import ButtonText from "../components/buttons/button-text/button-text";
import CompositionPhotos from "../components/composition-photos/composition-photos";
import SectionFeatures from "../components/section-feature/section-features";
import SectionTours from "../components/section-tours/section-tours";
import Col1of3 from "../components/layout/col-1-of-3";
import Card from "../components/section-tours/card/card";
import MainButton from "../components/buttons/main-button/main-button";
import Story from "../components/section-stories/story/story";
import SectionStories from "../components/section-stories/section-stories";
import CenterText from "../components/utilities/center-text/center-text";
import BackgroundVideo from "../components/background-video/background-video";
import SectionBook from "../components/section-book/section-book";
import Book from "../components/section-book/book/book";
import BookForm from "../components/section-book/book-form/book-form";
import Form from "../components/form/form";
import { useState } from "react";
import Footer from "../components/footer/footer";
import Navigation from "../components/navigation/navigation";
import PopUp from "../components/pop-up/pop-up";

export default function Home() {
  const [formData, setFormData] = useState(null);
  const [showPopup, setShowPopup] = useState(false);

  return (
    <div>
      <Head>
        <title>Natours</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="css/style.css" />
      </Head>

      <div className={styles.body}>
        <Navigation />

        <Header />

        <main>
          <SectionAbout>
            <CenterText className="u-margin-bottom-big">
              <HeadingSecondary>
                Exciting tours for adventurous people
              </HeadingSecondary>
            </CenterText>

            <Row>
              <Col1of2>
                <HeadingTertiary className="u-margin-bottom-small">
                  You are goint to fall in love with nature
                </HeadingTertiary>
                <Paragraph>
                  Lorem Ipsum is simply dummy text of the printing and
                  typesetting industry. Lorem Ipsum has been the industry's
                  standard dummy text ever since the 1500s, when an unknown
                  printer took a galley of type and scrambled it to make a type
                  specimen book.
                </Paragraph>

                <HeadingTertiary className="u-margin-bottom-small">
                  Live adventures like you never have before
                </HeadingTertiary>
                <Paragraph>
                  It has survived not only five centuries, but also the leap
                  into electronic typesetting, remaining essentially unchanged.
                </Paragraph>

                <ButtonText>Learn more</ButtonText>
              </Col1of2>

              <Col1of2>
                <CompositionPhotos />
              </Col1of2>
            </Row>
          </SectionAbout>

          <SectionFeatures></SectionFeatures>

          <SectionTours>
            <CenterText className="u-margin-bottom-big">
              <HeadingSecondary>Most popular tours</HeadingSecondary>
            </CenterText>

            <Row>
              <Col1of3>
                <Card
                  title="The Sea Explorer"
                  img_url="img/nat-5.jpg"
                  order="first"
                  price="297"
                  handleShowingPopup={() => setShowPopup(true)}
                >
                  <ul>
                    <li>3 day tours</li>
                    <li>Up to 30 people</li>
                    <li>2 tour guides</li>
                    <li>Sleepy in cozy hotels</li>
                    <li>Difficulty: easy</li>
                  </ul>
                </Card>
              </Col1of3>
              <Col1of3>
                <Card
                  title="The Forrest Hiker"
                  img_url="img/nat-6.jpg"
                  order="second"
                  price="497"
                  handleShowingPopup={() => setShowPopup(true)}
                >
                  <ul>
                    <li>7 day tours</li>
                    <li>Up to 40 people</li>
                    <li>6 tour guides</li>
                    <li>Sleep in provided tents</li>
                    <li>Difficulty: medium</li>
                  </ul>
                </Card>
              </Col1of3>
              <Col1of3>
                <Card
                  title="The Snow Adventure"
                  img_url="img/nat-7.jpg"
                  order="third"
                  price="897"
                  handleShowingPopup={() => setShowPopup(true)}
                >
                  <ul>
                    <li>5 day tours</li>
                    <li>Up to 15 people</li>
                    <li>3 tour guides</li>
                    <li>Sleep in provided tents</li>
                    <li>Difficulty: hard</li>
                  </ul>
                </Card>
              </Col1of3>
            </Row>
            <CenterText className="u-margin-top-big">
              <MainButton green={true}>Discover All Tours</MainButton>
            </CenterText>
          </SectionTours>

          <SectionStories>
            <BackgroundVideo sources={["img/video.mp4", "img/video.webm"]} />

            <CenterText className="u-margin-bottom-big" color="blue">
              <HeadingSecondary>
                We make people genuinely happy
              </HeadingSecondary>
            </CenterText>

            <Row>
              <Story
                userName="Mary Smith"
                img_url="img/nat-8.jpg"
                title="I had de best week ever with my family"
              >
                Vestibulum quis sem eu lacus blandit scelerisque. Donec nunc
                nibh, semper vitae nisi a, aliquam bibendum nulla. Integer ut
                odio efficitur, tristique tellus nec, tincidunt erat. Nulla
                facilisi. Morbi mattis eleifend nunc sit amet tristique. Etiam
                eros risus, mollis ac suscipit quis, gravida non arcu.
              </Story>
            </Row>

            <Row>
              <Story
                userName="Jack Wilson"
                img_url="img/nat-9.jpg"
                title="WOW! My life is completely different now"
              >
                Vestibulum quis sem eu lacus blandit scelerisque. Donec nunc
                nibh, semper vitae nisi a, aliquam bibendum nulla. Integer ut
                odio efficitur, tristique tellus nec, tincidunt erat. Nulla
                facilisi. Morbi mattis eleifend nunc sit amet tristique. Etiam
                eros risus, mollis ac suscipit quis, gravida non arcu.
              </Story>
            </Row>

            <CenterText className="u-margin-top-big">
              <ButtonText>Read all Stories</ButtonText>
            </CenterText>
          </SectionStories>

          <SectionBook>
            <Row>
              <Book bgImg="img/nat-10.jpg">
                <BookForm>
                  <HeadingSecondary className="u-margin-top-small">
                    Start booking now
                  </HeadingSecondary>
                  <Form
                    data={formData}
                    handleFormData={setFormData}
                    className="u-margin-top-medium"
                  />
                </BookForm>
              </Book>
            </Row>
          </SectionBook>

          <Footer />

          {showPopup ? (
            <PopUp onShowingPopup={() => setShowPopup(false)} />
          ) : null}
        </main>
      </div>
    </div>
  );
}
